baseURL = "https://help.geosync.cloud"
disableLanguages = []
googleAnalytics = ""
title = "GeoSync Help"
[Languages.en]
copyright = ""
languageCode = "en-us"
languageName = "En"
weight = 1
[Languages.en.params.banner]
bg_image = "images/banner.svg"
placeholder = "Have a question? Just ask here"
subtitle = "Find answers from our support team"
title = "GeoSync Help Center"
[Languages.en.params.cta]
content = "Let us know. We are always trying to add more information."
enable = true
title = "Didn't find an answer to your question?"
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "https://start.geosync.cloud/contact"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Help Center"
url = "/"
weight = 2
[[menu.main]]
name = "Z-Tools App"
parent = "Docs"
url = "z-tools-app"
weight = 10
[[menu.main]]
name = "Utility Solution"
parent = "Docs"
url = "utility-solution"
weight = 9
[[menu.main]]
name = "QGIS"
parent = "Docs"
url = "qgis"
weight = 8
[[menu.main]]
name = "Publisher App"
parent = "Docs"
url = "publisher-app"
weight = 7
[[menu.main]]
name = "GO Plus App"
parent = "Docs"
url = "go-plus-app"
weight = 6
[[menu.main]]
name = "GeoSync App"
parent = "Docs"
url = "geosync-app"
weight = 5
[[menu.main]]
name = "E911 Solution"
parent = "Docs"
url = "e911-solution"
weight = 4
[[menu.main]]
name = "E911 Solution"
parent = "Docs"
url = "e911-solution"
weight = 3
[[menu.main]]
name = "Campus Solution"
parent = "Docs"
url = "campus-solution"
weight = 2
[[menu.main]]
name = "AM Tools App"
parent = "Docs"
url = "am-tools-app"
weight = 1
[[menu.main]]
hasChildren = true
name = "Docs"
weight = 4
[[menu.main]]
name = "Home"
url = "https://start.geosync.cloud"
weight = 1
[params]
author = "GeoSync"
body_color = "#f9f9f9"
contact_form_action = "#"
description = "Flexible spatial framework for data management"
font_family = "lato"
image = "/icons/icon.png"
light_color = "#f8f9fa"
logo = "/icons/icon.png"
logo_white = ""
primary_color = "#00AB5F"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
[[params.social]]
icon = "ti-facebook"
link = "https://www.facebook.com/cdpky"
name = "Facebook"
[[params.social]]
icon = "ti-twitter-alt"
link = "https://twitter.com/cdpky"
name = "Twitter"
