################################# Default configuration ###################
# provide your domain here
baseURL = "https://help.geosync.cloud"
# site title
title = "GeoSync Help"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = "/icons/icon.png"
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# OpenGraph / Twitter Card metadata
description = "Flexible spatial framework for data management"
author = "GeoSync"
image = "/icons/icon.png" # this image will be used as fallback if a page has no image of its own

# customize color
primary_color = "#00AB5F"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
name = "Facebook"
link = "https://www.facebook.com/cdpky"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
name = "Twitter"
link = "https://twitter.com/cdpky"
  

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
copyright = ""

# banner
[Languages.en.params.banner]
title = "GeoSync Help Center"
subtitle = "Find answers from our support team"
bg_image = "images/banner.svg"
placeholder = "Have a question? Just ask here"

# call to action
[Languages.en.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Let us know. We are always trying to add more information."
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "contact us"
link = "https://start.geosync.cloud/contact"

############################# Menus ##############################

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Faq"
url = "faq"
weight = 2

# Dropdown menu
[[menu.main]]
weight = 3
name = "docs"
hasChildren = true

  [[menu.main]]
  parent = "docs"
  name = "AM Tools App"
  url = "am-tools-app"
  weight = 1

  [[menu.main]]
  parent = "docs"
  name = "Campus Solution"
  url = "campus-solution"
  weight = 2

  [[menu.main]]
  parent = "docs"
  name = "E911 Solution"
  url = "e911-solution"
  weight = 3

  [[menu.main]]
  parent = "docs"
  name = "E911 Solution"
  url = "e911-solution"
  weight = 4

  [[menu.main]]
  parent = "docs"
  name = "GeoSync App"
  url = "geosync-app"
  weight = 5

  [[menu.main]]
  parent = "docs"
  name = "GO Plus App"
  url = "go-plus-app"
  weight = 6

  [[menu.main]]
  parent = "docs"
  name = "Publisher App"
  url = "publisher-app"
  weight = 7

  [[menu.main]]
  parent = "docs"
  name = "QGIS"
  url = "qgis"
  weight = 8

  [[menu.main]]
  parent = "docs"
  name = "Utility Solution"
  url = "utility-solution"
  weight = 9

  [[menu.main]]
  parent = "docs"
  name = "Z-Tools App"
  url = "z-tools-app"
  weight = 10